#Bei Verbindungsfehler mit MySQL wird der Offline Modus gestartet
#Hier kann der Offline Modus konfiguriert werden

#Soll das Plugin Stoppen bei einem Verbindungsfehler?
stopPlugin: false


#Wenn im Offline Modus Daten in die Configs geschrieben werden, sind sie nicht syncronisiert
#mit der MySQL Datenbank

#Sollen die alten MySQL Configs überschrieben werden oder die MySQL Daten in die Localen Configs
#geschrieben werden
#
#   true: MySQL Configs überschrieben | false: Local Configs überschreiben
#
overwriteMySQLConfigs: true

#Sollen Konflikt-Kopien erstellt werden bei ungleichheiten zwischen Localen und MySQL Configs
createConflictCopies: true